import React, { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Inner from "./../../components/Layout/Inner";

const Index = () => {
  const router = useRouter();
  const [pageTitle, setPageTitle] = useState("About"); // Default title

  useEffect(() => {
    // Listen for route changes
    const handleRouteChange = (url) => {
      // Set the title based on the new URL
      if (url === "/contact") {
        setPageTitle("Contact");
      }else if (url === "/") {
        setPageTitle("Home");
      } else if (url === "/work") {
        setPageTitle("Work");
      } else if (url === "/about") {
        setPageTitle("About");
      } // Add more routes as needed
    };

    // Subscribe to route changes
    router.events.on("routeChangeComplete", handleRouteChange);

    // Clean up the subscription
    return () => {
      router.events.off("routeChangeComplete", handleRouteChange);
    };
  }, [router.events]);

  return (
    <>
      <Head>
        <title>Kshitij Guladhe &#x2022; Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="fevicon.png" />
      </Head>

      <Inner pageTitle={pageTitle}>
        <div style={{ marginTop: "5rem" }}>About</div>
        <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit...</h1>
      </Inner>
    </>
  );
};

export default Index;
